name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

   
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: userdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d userdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      
      PYTHONPATH: ${{ github.workspace }}
      
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/userdb
      JWT_SECRET: devsecret
      JWT_EXPIRE_MINUTES: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q
